#!/bin/bash

# Define your angular module name here
MODULE=Androguide

# Colors for the console output
YELLOW="\\E[33;44m"
GREEN="\\033[1;32m"
RED="\\033[1;31m"
RESET="\\e[0m"

set -e

# No view name was passed, abort.
if [ -z "$1" ]; then
    echo -n -e "${RED}Usage: ./create_view <view name>${RESET}\n"
    exit

# We have a view name, create the boilerplate
else
    echo -n -e "${YELLOW}Generating $1 view, controller and style...${RESET}\n"

    # Create files
    touch app/views/$1.html
    touch app/styles/views/$1.scss
    touch app/styles/views/$1.css
    touch app/scripts/controllers/$1.js

    # Add a script tag to the index.html for the new controller
    sed -i 's/<!--Controllers-->/<!--Controllers-->\n<\script \src=\"\script\s\/controller\s\/'${1}'.js\"><\/\script>/g' app/index.html

    # Add boilerplate code to the controller
    echo -e "angular.module('"${MODULE}"').controller('"${1}"Ctrl', ['\$scope', function(\$scope) {\n\n}]);" > app/scripts/controllers/$1.js

    # Done
    echo -n -e "${GREEN}Done.${RESET}\n"
fi