// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var app, errorHandler, express, port;

  express = require("express");

  app = express();

  errorHandler = require("errorhandler");

  port = parseInt(process.env.PORT, 10) || 4567;

  app.use(express["static"](__dirname + "/app/dist"));

  app.use(errorHandler({
    dumpExceptions: true,
    showStack: true
  }));

  app.listen(port);

  console.log("Server listening on port: " + port);

}).call(this);

//# sourceMappingURL=server.map
